version: 2

jobs:
  build:
    # docker image 
    docker:
      - image: circleci/node:11.9.0
    # branches:
    #   only:
    #     - master

    # working_directory: ~/repo

    steps:
      # checkout source code
      - checkout
      # restore liblary cache
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-

      # yarn install
      - run: yarn install
      - run: yarn add firebase-tools

      # save cache
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # yarn build
      - run: yarn build

      # deploy
      - run: node_modules/.bin/firebase deploy --project $FIREBASE_PJ --token $FIREBASE_TOKEN

workflows:
  version: 2
  build_and_dploy:
    jobs:
      - build:
          filters:
            branches:
              only: master